[project]
name = "peerpear"
version = "0.1.0"
description = ""
authors = [
    {name = "Sungmin Kim",email = "sk3378@princeton.edu"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "flask[async] (>=3.1.2,<4.0.0)",
    "flask-cors (>=6.0.1,<7.0.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "psycopg[binary] (>=3.2.11,<4.0.0)",
    "alembic (>=1.17.0,<2.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "pydantic (>=2.12.3,<3.0.0)",
    "uuid (>=1.30,<2.0)",
    "logging (>=0.4.9.6,<0.5.0.0)",
    "asyncio (>=4.0.0,<5.0.0)",
    "redis (>=6.4.0,<7.0.0)",
    "contextvars (>=2.4,<3.0)",
    "tenacity (>=9.1.2,<10.0.0)",
    "google (>=3.0.0,<4.0.0)",
    "google-genai (>=1.45.0,<2.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "greenlet (>=3.2.4,<4.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "supabase (>=2.24.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false